<script>
 import { page } from '$app/stores'; import { onMount } from 'svelte'; import { isSaved,toggleWatchlist } from '$lib/store';
 let item=null; let loading=true; let error=''; let selected=1; let episodes=[]; let saved=false;
 async function load(){try{const id=$page.params.id;const r=await fetch(`https://api.jikan.moe/v4/anime/${id}/full`);if(!r.ok)throw Error();item=(await r.json()).data;episodes=Array.from({length:item?.episodes||12},(_,i)=>i+1);saved=isSaved(item.mal_id)}catch(e){error='Anime details could not be loaded.'}finally{loading=false}}
 function save(){saved=toggleWatchlist({id:item.mal_id,title:item.title,image:item.images?.jpg?.large_image_url,type:item.type,episodes:item.episodes})}
 onMount(load);
</script>
<svelte:head><title>{item ? `${item.title} — AniVerse` : 'Anime — AniVerse'}</title></svelte:head>
{#if loading}<div class="state">Loading anime details…</div>{:else if error}<div class="state">{error}</div>{:else if item}<div class="page"><div class="top"><a class="back" href="/">← Back to AniVerse</a><a class="list" href="/watchlist">♡ My Watchlist</a></div><section class="hero"><img class="cover" src={item.images?.jpg?.large_image_url} alt={item.title}/><div><p class="tag">{item.status||'Anime'}</p><h1>{item.title}</h1><p class="meta">★ {item.score??'N/A'} · {item.type||'TV'} · {item.episodes||'?'} episodes</p><p class="synopsis">{item.synopsis||'No synopsis available.'}</p><div class="chips">{#each (item.genres||[]).slice(0,6) as g}<span>{g.name}</span>{/each}</div><button class="save" class:saved on:click={save}>{saved?'♥ Saved to Watchlist':'♡ Add to Watchlist'}</button></div></section><section class="watch"><div class="watchHead"><div><small>EPISODES</small><h2>Choose an episode</h2></div><span>{episodes.length} episodes</span></div><div class="episodes">{#each episodes as ep}<a class:chosen={selected===ep} on:click={()=>selected=ep} href={`/watch/${item.mal_id}/${ep}`}>EP {ep}</a>{/each}</div></section></div>{/if}
<style>:global(body){margin:0;background:#08090d;color:#f5f5f7;font-family:Inter,system-ui,sans-serif}.page{min-height:100vh;max-width:1250px;margin:auto;padding:35px 5vw 80px}.top{display:flex;justify-content:space-between}.back,.list{color:#9b7cff;font-size:14px;text-decoration:none}.hero{display:grid;grid-template-columns:250px 1fr;gap:35px;margin-top:35px;align-items:center}.cover{width:250px;aspect-ratio:2/3;object-fit:cover;border-radius:15px;border:1px solid #ffffff12}.tag,small{color:#9b7cff;font-size:11px;font-weight:800;letter-spacing:2px}h1{font-size:clamp(38px,5vw,65px);line-height:1;margin:10px 0;letter-spacing:-3px}.meta{color:#f0d58b;font-weight:700}.synopsis{max-width:750px;color:#9698a5;line-height:1.75}.chips{display:flex;gap:8px;flex-wrap:wrap}.chips span{padding:7px 11px;border:1px solid #292b34;border-radius:999px;color:#aaa;font-size:12px}.save{margin-top:20px;padding:11px 15px;border:1px solid #393040;background:#15131c;color:#d8cfff;border-radius:9px;cursor:pointer}.save.saved{background:#8d6cf1;color:#fff}.watch{margin-top:65px}.watchHead{display:flex;justify-content:space-between;align-items:end}.watchHead h2{margin:8px 0 25px;font-size:30px}.watchHead span{color:#686a76;font-size:13px}.episodes{display:grid;grid-template-columns:repeat(8,1fr);gap:10px}.episodes a{padding:13px 8px;text-align:center;background:#111218;border:1px solid #292b34;border-radius:9px;color:#aaa;font-size:12px;text-decoration:none}.episodes a:hover,.episodes a.chosen{background:#8d6cf1;border-color:#8d6cf1;color:white}.state{min-height:100vh;display:grid;place-items:center;background:#08090d;color:#aaa}@media(max-width:700px){.hero{grid-template-columns:1fr}.cover{width:180px}.episodes{grid-template-columns:repeat(4,1fr)}h1{letter-spacing:-2px}}
</style>