<script>
 import { page } from '$app/stores'; import { onMount } from 'svelte'; import { getHistory,saveProgress } from '$lib/store';
 $: id=$page.params.id; $: episode=+$page.params.episode||1; let anime=null; let progress=0; let title='Anime';
 async function load(){try{const r=await fetch(`https://api.jikan.moe/v4/anime/${id}`);if(r.ok){anime=(await r.json()).data;title=anime.title;}}catch{} const old=getHistory().find(x=>String(x.id)===String(id));progress=old?.progress||0;}
 function mark(p){progress=Math.max(0,Math.min(100,p));saveProgress({id,title,image:anime?.images?.jpg?.large_image_url,episode,progress});}
 onMount(load);
</script>
<svelte:head><title>{title} — Episode {episode} — AniVerse</title></svelte:head>
<div class="page"><header><a class="brand" href="/">AniVerse</a><div><a href="/watchlist">♡ Watchlist</a><a href="/anime/{id}">← Details</a></div></header><main><div class="crumb">WATCHING · {title}</div><div class="player"><div class="play">▶</div><h2>Episode {episode}</h2><small>Licensed / officially provided video source goes here.</small></div><div class="progress"><span style={`width:${progress}%`}></span></div><div class="controls"><button on:click={()=>mark(Math.min(100,progress+10))}>＋ Save progress</button><span>{progress}% watched</span></div><div class="bar"><a href="/watch/{id}/{Math.max(1,episode-1)}">← Previous</a><strong>Episode {episode}</strong><a href="/watch/{id}/{episode+1}">Next →</a></div><section><h2>{title}</h2><p>Your episode progress is saved locally on this browser so you can continue later.</p></section></main></div>
<style>:global(body){margin:0;background:#08090d;color:#f5f5f7;font-family:Inter,system-ui,sans-serif}.page{min-height:100vh;padding:0 5vw 70px}header{height:76px;display:flex;align-items:center;justify-content:space-between;border-bottom:1px solid #ffffff0b}header a{color:#aaa;text-decoration:none;margin-left:20px}.brand{font-weight:900!important;color:white!important;font-size:21px}.crumb{color:#9b7cff;font-size:11px;font-weight:800;letter-spacing:2px;margin-bottom:18px}main{max-width:1200px;margin:35px auto}.player{aspect-ratio:16/9;background:#111218;border:1px solid #292b34;border-radius:15px;display:grid;place-items:center;text-align:center;box-shadow:0 20px 70px #0008}.play{width:68px;height:68px;border-radius:50%;display:grid;place-items:center;background:#8d6cf1;font-size:25px;padding-left:4px}.player h2{margin:-15px 0 0}.player small{color:#777;max-width:450px}.progress{height:5px;background:#202129;border-radius:99px;margin-top:12px;overflow:hidden}.progress span{display:block;height:100%;background:#8d6cf1}.controls{display:flex;justify-content:space-between;align-items:center;padding:14px 0;color:#777;font-size:13px}.controls button{border:1px solid #302b3b;background:#15131c;color:#cfc3ff;border-radius:8px;padding:8px 12px;cursor:pointer}.bar{display:flex;justify-content:space-between;align-items:center;padding:18px 0;border-bottom:1px solid #ffffff0b}.bar a{color:#9b7cff;text-decoration:none}.bar strong{font-size:14px}section{margin-top:45px;color:#8e909c}section h2{color:white}section p{line-height:1.7}
</style>